export const REPAYMENT_UPLOAD_REQUEST = 'REPAYMENT_UPLOAD_REQUEST';
export const REPAYMENT_UPLOAD_SUCCESS = 'REPAYMENT_UPLOAD_SUCCESS';
export const REPAYMENT_UPLOAD_ERROR = 'REPAYMENT_UPLOAD_ERROR';

export const CUSTOMER_SUMMARIES_REQUEST = 'CUSTOMER_SUMMARIES_REQUEST';
export const CUSTOMER_SUMMARIES_SUCCESS = 'CUSTOMER_SUMMARIES_SUCCESS';
export const CUSTOMER_SUMMARIES_ERROR = 'CUSTOMER_SUMMARIES_ERROR';

export const REPAYMENT_DETAILS_REQUEST = 'REPAYMENT_DETAILS_REQUEST';
export const REPAYMENT_DETAILS_SUCCESS = 'REPAYMENT_DETAILS_SUCCESS';
export const REPAYMENT_DETAILS_ERROR = 'REPAYMENT_DETAILS_ERROR';

export const UPDATE_SPINNER_STATUS = 'UPDATE_SPINNER_STATUS';
 